### ISSUE TITLE
Updating the code the "normal" way

### ISSUE THREAD

**Issue by jm-c** [climate-machine/Oceananigans.jl#598] opened 2020-01-22 04:48 UTC
Had an earlier clone, was on master branch, everything was in order as "git status" 
  
  nothing to commit, working tree clean

Then I updated my clone the usual way, just typing "git pull", but got plenty of warnings about
conflicts and so on. After that, "git status" reports:

  On branch master
   Your branch and 'origin/master' have diverged,
   and have 1106 and 2212 different commits each, respectively.
    (use "git pull" to merge the remote branch into yours)
  You have unmerged paths.
    (fix conflicts and run "git commit")
    (use "git merge --abort" to abort the merge)

so it looks like I am far from a clean update.

My question: how to proceed when trying to update my Oceananigans local clone and
why the standard way does not work for this repos ?

**Comment by ali-ramadhan** [comment] 2020-01-22 11:21
Ah sorry this must be related to https://github.com/climate-machine/Oceananigans.jl/issues/509 where I rewrote git history using [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to remove some big JLD2 files that were accidentally pushed and blew up the size of the repository (500 MB+).

But after rewriting git history everyone has to delete their local version of the repository and `git clone` a fresh copy.

I think I cc'ed some people in the issue to warn them about this but didn't realize you still had an active copy, sorry about that!

**Comment by christophernhill** [comment] 2020-01-22 12:32
I had to do the same.

Chris

**Comment by ali-ramadhan** [comment] 2020-01-22 12:44
Ah sorry about that. Don't think we'll have to do it again as all the damage happens in the `gh-pages` branch which stores documentation, but will make sure to cc you guys on things like this.

**Comment by jm-c** [comment] 2020-01-22 14:49
OK, thanks for the useful piece of information. Just for completeness, issue #509 was closed on Dec 09, 2019 and the 2 related PR #524 and PR #558 were merged in on Nov 03 and Dec 09, 2019 respectively.

**Comment by christophernhill** [comment] 2020-01-22 14:58
@ali-ramadhan would it be good to send messages to everyone who has a fork maybe and maybe keep an issue open, so people who have cloned can see? Of course it would also be good not to rewrite the history - that pretty much breaks how git works. In theory reviewing PRs should catch this?

**Comment by ali-ramadhan** [comment] 2020-01-22 15:22
> @ali-ramadhan would it be good to send messages to everyone who has a fork maybe and maybe keep an issue open, so people who have cloned can see?

That's a good idea, I think the only other person who had an issue was @arcavaliere who had an open PR at the time, but otherwise we could tag all the forkers.

> Of course it would also be good not to rewrite the history - that pretty much breaks how git works. In theory reviewing PRs should catch this?

Agreed. Yeah it took us a while to find the leak in #509 (JLD2 file wasn't added by us but by examples generating files when built) and the damage was contained to the `gh-pages` branch but the reason it affected the `master` branch was that I also deleted an old regression test file.

Now that we're more aware of this issue I think we can stop it from happening again.

**Comment by ali-ramadhan** [comment] 2020-02-15 13:51
Guessing this isn't an issue anymore so closing.

**Closed by ali-ramadhan** 2020-02-15 13:51 UTC
Labels: bug
